name: 🚨 auto-update

on:

  workflow_dispatch:

  schedule:

    - cron:  0 */4 * * *

jobs:

  build:

    name: auto update

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - uses: SummerSec/github-profile-terminal-action@main

      with:

        feed_url: https://sumsec.me/resources/sitemap.xml

        twitter_username: SecSummers

        theme: dark

        token: ${{ secrets.RELEASE }}

        file_path: README.md

    - name: generate-snake-game-from-github-contribution-grid

      uses: Platane/snk@v2.0.0-rc.2

      with:

        github_user_name: ${{ github.repository_owner }}

        outputs: |

          dist/github-snake.svg

          dist/github-snake-dark.svg?palette=github-dark

          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    - name: push github-contribution-grid-snake.svg to the output branch


      uses: crazy-max/ghaction-github-pages@v3.1.0

      with:

        target_branch: master

        author: SummerSec@users.noreply.github.com

        committer: SummerSec@users.noreply.github.com

        commit_message: ":beers: Update Commit And Fix GIF"

        build_dir: .

      env:

        GITHUB_TOKEN: ${{ secrets.RELEASE }}
