name: 🚨 auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 */4 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: SummerSec/github-profile-terminal-action@main
      with:
        feed_url: https://sumsec.me/resources/sitemap.xml
        twitter_username: SecSummers
        theme: dark
        token: ${{ secrets.RELEASE }}
        file_path: README.md
    - name: generate-snake-game-from-github-contribution-grid
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
    - name: push github-contribution-grid-snake.svg to the output branch
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        target_branch: master
        #author: SummerSec@users.noreply.github.com
        build_dir: .
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}
   
#     - uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         # Optional. Commit message for the created commit.
#         # Defaults to "Apply automatic changes"
#         commit_message: Automated Change
#         # Optional. Options used by `git-commit`.
#         # See https://git-scm.com/docs/git-commit#_options
#         commit_options: '--no-verify --signoff'
#         branch: output

#         # Optional. Local file path to the repository.
#         # Defaults to the root of the repository.
#         repository: .

#         # Optional commit user and author settings
#         commit_user_name: Summersec # defaults to "github-actions[bot]"
#         commit_user_email: SummerSec@users.noreply.github.com # defaults to "github-actions[bot]@users.noreply.github.com"
#         commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

        

#         # Optional. Disable dirty check and always try to create a commit and push
#         skip_dirty_check: true    



