name: 🚨 auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 */4 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: SummerSec/github-profile-terminal-action@main
      with:
        feed_url: https://sumsec.me/resources/sitemap.xml
        twitter_username: SecSummers
        theme: dark
        token: ${{ secrets.RELEASE }}
        file_path: README.md
    - name: generate-snake-game-from-github-contribution-grid
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
#     - name: push github-contribution-grid-snake.svg to the output branch
#       uses: crazy-max/ghaction-github-pages@v3.1.0
#       with:
#         target_branch: master
#         author: SummerSec
#         committer: SummerSec@users.noreply.github.com
#         commit_message: ":beers: Update Commit And Fix GIF"
#         build_dir: .
#       env:
#         GITHUB_TOKEN: ${{ secrets.RELEASE }}
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: '.'

        # The name of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        # author_name: user_info

        # The email of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        # author_email: SummerSec@users.noreply.github.com

        # The name of the custom committer you want to use, if different from the author of the commit.
        # Default: the name of the author (set with either author_name or default_author)
        # committer_name: SummerSec

        # The email of the custom committer you want to use, if different from the author of the commit.
        # Default: the email of the author (set with either author_email or default_author)
        # committer_email: SummerSec@users.noreply.github.com


        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actor


        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Commit from GitHub Actions Auto Actions'

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: ignore
#     - uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         # Optional. Commit message for the created commit.
#         # Defaults to "Apply automatic changes"
#         commit_message: Automated Change
#         # Optional. Options used by `git-commit`.
#         # See https://git-scm.com/docs/git-commit#_options
#         commit_options: '--no-verify --signoff'
#         branch: output

#         # Optional. Local file path to the repository.
#         # Defaults to the root of the repository.
#         repository: .

#         # Optional commit user and author settings
#         commit_user_name: Summersec # defaults to "github-actions[bot]"
#         commit_user_email: SummerSec@users.noreply.github.com # defaults to "github-actions[bot]@users.noreply.github.com"
#         commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

        

#         # Optional. Disable dirty check and always try to create a commit and push
#         skip_dirty_check: true    



